SELECT GRANDCHILD.ID
FROM ECOLI_DATA PARENT
JOIN ECOLI_DATA CHILD
ON PARENT.ID = CHILD.PARENT_ID
JOIN ECOLI_DATA GRANDCHILD
ON CHILD.ID = GRANDCHILD.PARENT_ID
WHERE PARENT.PARENT_ID IS NULL
ORDER BY 1