-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
    AND DURATION_TYPE = '30일 이상'
) P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < '2022-12-01' AND END_DATE >= '2022-11-01'
)
AND (C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) >= 500000 AND (C.DAILY_FEE * (100 - P.DISCOUNT_RATE) / 100 * 30) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC
 