WITH USER_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), TOTAL_2021 AS (
    SELECT COUNT(*) AS TOTAL_CNT
    FROM USER_2021
)

SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT O.USER_ID) / T.TOTAL_CNT, 1) AS PUCHASED_RATIO
FROM USER_2021 U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
CROSS JOIN TOTAL_2021 T
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR, MONTH