SELECT
    E.EMP_NO,
    E.EMP_NAME,
    CASE
        WHEN T.SCORE >= 96 THEN 'S'
        WHEN T.SCORE >= 90 THEN 'A'
        WHEN T.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN T.SCORE >= 96 THEN E.SAL * 0.2
        WHEN T.SCORE >= 90 THEN E.SAL * 0.15
        WHEN T.SCORE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS T
ON E.EMP_NO = T.EMP_NO
ORDER BY 1