-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
JOIN (
    SELECT MEMBER_ID, COUNT(*) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.COUNT = (
    SELECT MAX(C.COUNT)
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) C
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT