SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA PARENT
JOIN ECOLI_DATA CHILD
ON PARENT.ID = CHILD.PARENT_ID
WHERE CHILD.PARENT_ID IS NOT NULL
AND CHILD.GENOTYPE & PARENT.GENOTYPE >= PARENT.GENOTYPE
ORDER BY CHILD.ID