-- 코드를 입력하세요
SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
) M
ON F.CATEGORY = M.CATEGORY
AND F.PRICE = M.MAX_PRICE
ORDER BY F.PRICE DESC